### ISSUE TITLE
Remove allorigins proxy and use the beacons API directly

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-beacons-map-table#5]
- [x] Fetch data from the beacon API directly @Piiit 
- [x] Generate a new dist file (....min.js) @Piiit 
- [x] Upload the new version to the CDN @Piiit 
> We use jsdelivr which takes the latest version directly from our GitHub (see README)

This is related to https://github.com/noi-techpark/beacon-suedtirol-api/issues/38, which is also fixed now.

**Comment by Piiit** [comment]
@danielrampanelli Done. Please test... Just check if everything on maps.beacon.bz.it works as expected

**Comment by danielrampanelli** [comment]
Apart from the caching issue when only referencing the @master branch (shouldn't be longer than 24h), everything seems to work as expected!

**Comment by Piiit** [comment]
@danielrampanelli Thx, I move it to done then
