### ISSUE TITLE
Wrong Zoom Level?

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/webcomp-beacons-map-table#8]
Since today I noticed the map opens with a high zoom in factor.

Even after a browser refresh and in an anonymous browser session the high zoom factor keeps on.

![Screenshot from 2019-07-15 18-18-56](https://user-images.githubusercontent.com/414797/61231791-1f2e3680-a72d-11e9-9ae2-425d9fca8570.png)

**Comment by danielrampanelli** [comment]
Couldn't reproduce it on my testing environments, but the recent (pending) changes should address and hopefully fix this issue.

**Comment by Piiit** [comment]
@danielrampanelli With Firefox everything is OK, but Chrome and Chromium show this issue. At least on Windows and Linux.

**Comment by danielrampanelli** [comment]
As soon as the changes are propagated to the CDN, the recent changes should resolve and fix this issue.

**Comment by danielrampanelli** [comment]
When using jsDelivr there seems to be a caching system in place, but it seems there's a way to [purge the cache via the API](https://github.com/jsdelivr/jsdelivr#purge-cache) in case waiting for the expiration of the asset is not an option.

**Comment by danielrampanelli** [comment]
This has been checked and tested on the following browsers and everything seems to be working correctly: Chrome (Mac, Windows, Linux), Firefox (Mac, Windows, Linux), Safari (Mac, iOS).

**Comment by Piiit** [comment]
Works now, thank you

**Comment by Piiit** [comment]
> When using jsDelivr there seems to be a caching system in place and it seems there's a way to [purge the cache via the API](https://github.com/jsdelivr/jsdelivr#purge-cache) in case waiting for the expiration of the asset is not an option.

Thanks for that information, but we decided to just wait as long as it needs. At the end of this year we will have our own server to serve web components.
